name: Deploy
on:
  release:
    types: [published]

jobs:
  npm:
    runs-on: ubuntu-latest
    needs: 'Test.quality'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

