name: Test, Build and Deploy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Check TS
        run: yarn tsc

      - name: Lint
        run: yarn lint

      - name: Test and Deploy Coverage
        run: yarn jest --coverage

      - name: Deploy Coverage
        uses: coverallsapp/github-action@master
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
